Add course page
RobertBrunhage/website pull request #69
Opened 2021-08-06 16:41 UTC by JohnHilding

2021-08-06 17:21 UTC, RobertBrunhage commented
Noice!

What I've seen so far that needs fixes.

1. The route and link should be **course** and not **courses**
2. The about me section seems more indented the the other sections
3. The "WHAT YOU GET" box is not rounded

2021-08-06 19:25 UTC, RobertBrunhage commented
- The landing page seems a bit affected with the font size change
![image](https://user-images.githubusercontent.com/26344867/128561261-9347e2bd-9023-4912-8317-af529a56e4d6.png)

- Change the text on buttons from "ENROLL NOW" to what we currently have on Figma
- The last button on mobile should be below the "When you sign up you are also eligible to win this course" text

2021-08-07 16:12 UTC, RobertBrunhage requested changes
Some small things I noticed.

2021-08-07 16:12 UTC, RobertBrunhage commented on pages/course.tsx
> +          <meta property="og:url" content="https://robertbrunhage.com/courses" />
```suggestion
          <meta property="og:url" content="https://robertbrunhage.com/course" />
```

2021-08-07 16:12 UTC, RobertBrunhage commented on pages/course.tsx
> +          <link rel="prefetch" href="https://robertbrunhage.com/videos" />
```suggestion
          <link rel="prefetch" href="https://robertbrunhage.com/course" />
```

2021-08-07 16:12 UTC, RobertBrunhage commented on pages/course.tsx
> +          <link rel="canonical" href="https://robertbrunhage.com" />
```suggestion
          <link rel="canonical" href="https://robertbrunhage.com/course" />
```

2021-08-07 16:12 UTC, RobertBrunhage commented on pages/course.tsx
> +                expert this course fasttrack your Flutter journey.
```suggestion
                expert this course will fast track your Flutter journey.
```

2021-08-07 16:12 UTC, RobertBrunhage commented on pages/course.tsx
> +                  I’m Robert Brunhage. You may know me by my <strong>YouTube channel</strong> or
Make the YouTube channel text a link to the channel

2021-08-07 16:26 UTC, JohnHilding commented on pages/course.tsx
> +          <link rel="prefetch" href="https://robertbrunhage.com/videos" />
no

2021-08-07 16:29 UTC, RobertBrunhage approved these changes
Nice, tyty

2021-08-07 16:44 UTC, RobertBrunhage requested changes
Some more things :)

2021-08-07 16:44 UTC, RobertBrunhage commented on components/emailForm/forms/emailList.tsx
> +        description="Level up your skills by joining 600 other Flutter developers now! 😃"
```suggestion
        description="Level up your skills by joining 1000 other Flutter developers now! 😃"
```

2021-08-07 16:44 UTC, RobertBrunhage commented on pages/course.tsx
> +          <meta property="twitter:description" content="Flutter Courses" />
```suggestion
          <meta property="twitter:description" content="Build a complete production ready Flutter application!" />
```

2021-08-07 16:44 UTC, RobertBrunhage commented on pages/course.tsx
> +                  "https://gmail.us2.list-manage.com/subscribe/post?u=ff73d806dd2f49da87ede8337&amp;id=ed4e712aca&amp;SIGNUP=FlutterMovieCourse"
Make this action url a const, and replace all the magic strings with the const

2021-08-07 16:44 UTC, RobertBrunhage commented on pages/course.tsx
> +                    "https://gmail.us2.list-manage.com/subscribe/post?u=ff73d806dd2f49da87ede8337&amp;id=ed4e712aca&amp;SIGNUP=FlutterMovieCourse"
Same here

2021-08-07 16:50 UTC, RobertBrunhage approved these changes

2021-08-07 16:50 UTC, merged